Docstrings -> Google style for mkdocs render
datajoint/workflow-deeplabcut pull request #14
Opened 2022-10-14 23:37 UTC by CBroz1

2022-10-18 16:04 UTC, kabilar requested changes
Thanks @CBroz1.  Please also update the readme to simplify similar to the recent changes in https://github.com/datajoint/element-deeplabcut/pull/53.

2022-10-20 20:05 UTC, kabilar commented
Please add a class docstring for the `Device` table in `pipeline.py`.

2022-10-27 17:23 UTC, kabilar requested changes
Thanks @CBroz1.  I have reviewed a couple of files and have minor comments below.

@kushalbakshi Please review the docstrings and merge when you are ready.

2022-10-27 17:23 UTC, kabilar commented on CHANGELOG.md
>  ## 0.1.1 - Unreleased
```suggestion
## [0.1.1] - 2022-10-27
```

2022-10-27 17:23 UTC, kabilar commented on README.md
> +[Element documentation](datajoint.com/docs/elements/element-deeplabcut).
```suggestion
Installation and usage instructions can be found at the 
[Element documentation](datajoint.com/docs/elements/element-deeplabcut).
```

2022-10-27 17:23 UTC, kabilar commented on README.md
> +tables that can be combined with other Elements to assemble a fully functional pipeline.
```suggestion
The DataJoint Workflow for DeepLabCut combines multiple DataJoint Elements for markerless pose estimation with
[DeepLabCut](https://www.deeplabcut.org/).  DataJoint Elements collectively standardize
and automate data collection and analysis for neuroscience experiments.  Each Element is
a modular pipeline for data storage and processing with corresponding database
tables that can be combined with other Elements to assemble a fully functional pipeline.
```

2022-10-27 17:23 UTC, kabilar commented on CHANGELOG.md
>  ## 0.1.1 - Unreleased
Please also add the link to the bottom of the file:
```
[0.1.1]: https://github.com/datajoint/workflow-deeplabcut/releases/tag/0.1.1
```

2022-10-27 19:08 UTC, kushalbakshi approved these changes

2022-10-27 19:10 UTC, merged