Updates for element PR #15 `RecordingInfo` table
datajoint/workflow-deeplabcut pull request #8
Opened 2022-04-18 16:16 UTC by CBroz1

2022-04-18 20:52 UTC, ttngu207 approved these changes

2022-05-06 22:20 UTC, CBroz1 commented
Additional updates to Equipment table per [datajoint elements issue 83](https://github.com/datajoint/datajoint-elements/issues/83)

2022-05-10 15:01 UTC, kabilar commented on workflow_deeplabcut/pipeline.py
> +class Equipment(dj.Manual):
Thanks @CBroz1.  Please update `element-deeplabcut` to mirror this change.

2022-05-10 15:06 UTC, kabilar commented on workflow_deeplabcut/pipeline.py
> +    contents = [[1, 'Pose Estimation'], [2, 'Pose Estimation']]
Instead of an id for the `equipment` attribute, should we use a description about the camera?

2022-05-10 15:21 UTC, kabilar commented on workflow_deeplabcut/ingest.py
> +    print(f'\n---- Inserting {insert_length} entry(s) into _recording_info ----')
Please move this populate step to a `process.py` script.

2022-05-10 15:32 UTC, kabilar commented on notebooks/py_scripts/04-Automate_Optional.py
> +model.RecordingInfo.populate()
For the `04-automate` notebook, let's wrap all of the populate statements within a `process.py` script.

2022-05-10 15:44 UTC, kabilar commented on notebooks/py_scripts/03-Process.py
> +       'recording_id': '1', 'camera_id': 1}
```suggestion
key = {'subject': 'subject6',
       'session_datetime': '2021-06-02 14:04:22',
       'recording_id': '1', 'equipment': 1}
```

2022-05-10 15:45 UTC, kabilar commented on notebooks/py_scripts/03-Process.py
> +model.VideoRecording.File.insert1(key, ignore_extra_fields=True)
Since this is a didactic notebook, I would suggest only inserting the attributes specific to this table.

2022-05-10 16:00 UTC, kabilar requested changes
Thanks @CBroz1!  Great work.  A few minor suggestions above.

2022-05-10 18:31 UTC, CBroz1 commented
Thanks for your review @kabilar - I've added a `process.py` script and changes the corresponding notebook to include use.

One notable issue is that the `ingest_csv_to_table` function did not install when I ran `pip install git+<interface URL>`, so I've duplicated that function here

2022-05-10 18:31 UTC, CBroz1 commented on workflow_deeplabcut/pipeline.py
> +    contents = [[1, 'Pose Estimation'], [2, 'Pose Estimation']]
I added camera descriptions for clarity, and changed the primary keys to `Camera1` and `Camera2`

2022-05-10 19:00 UTC, kabilar commented on CHANGELOG.md
> +## 0.0.0a1 - 2022-05-10
```suggestion
## 0.1.0 - 2022-05-10
```

2022-05-10 19:02 UTC, kabilar commented on CHANGELOG.md
> ++ Proccess.py script
```suggestion
+ Process.py script
```

2022-05-10 19:05 UTC, kabilar commented on CHANGELOG.md
> +## 0.0.0a1 - 2022-05-10
Let's remove the pre-release tag.

2022-05-10 19:06 UTC, kabilar commented on docker/docker-compose-dev.yaml
> +    image: workflow-deeplabcut-dev:0.0.0a1
```suggestion
    image: workflow-deeplabcut-dev:0.1.0
```

2022-05-10 19:06 UTC, kabilar commented on docker/docker-compose-test.yaml
> +    image: workflow-deeplabcut-test:0.0.0a1
```suggestion
    image: workflow-deeplabcut-test:0.1.0
```

2022-05-10 19:07 UTC, kabilar commented on workflow_deeplabcut/version.py
> +__version__ = '0.0.0a1'
```suggestion
__version__ = '0.1.0'
```

2022-05-10 19:21 UTC, kabilar commented on notebooks/py_scripts/03-Process.py
> +_ = key.pop('equipment') # get rid of secondary key from master table
```suggestion
key.pop('equipment') # get rid of secondary key from master table
```

2022-05-10 19:28 UTC, kabilar commented on workflow_deeplabcut/process.py
> +    """If verbose set to false, used to quiet tear_down table.delete prints"""
```suggestion
    """If verbose set to false, used to quiet populate."""
```

2022-05-10 20:15 UTC, kabilar commented on workflow_deeplabcut/process.py
> +
```suggestion
import sys
```

2022-05-10 20:17 UTC, kabilar commented on workflow_deeplabcut/process.py
> +
```suggestion
import os
```

2022-05-10 20:46 UTC, kabilar approved these changes
Thanks @CBroz1!

2022-05-10 20:46 UTC, merged